import Media from "./Media";
import ProductBrand from "./ProductBrand";
import ProductGroup from "./ProductGroup";
import ProductProperty from "./ProductProperty";

interface Product {
  id: number;
  name: string;
  barcode: string;
  location: string;
  costOfGoods: number; // originalPrice
  sellingPrice: number;
  quantity: number;
  status: string;
  description: string;
  note: string;
  minInventoryThreshold: number; // minQuantity
  maxInventoryThreshold: number; // maxQuantity
  productGroup: string;
  productBrand: string;
  productProperty: string;
  images: Set<Media>;
}

export default Product;

export const sampleProducts: Product[] = [
  {
    id: 2,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 3,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 4,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
  {
    id: 5,
    name: "Another Sample Product",
    barcode: "XYZ789",
    location: "Aisle 2, Shelf 3",
    costOfGoods: 15.0,
    sellingPrice: 25.0,
    quantity: 50,
    status: "In Stock",
    description: "Another sample product description.",
    note: "Additional notes for the second product.",
    minInventoryThreshold: 5,
    maxInventoryThreshold: 100,
    productGroup: "Clothing",
    productBrand: "Another Brand",
    productProperty: "Medium",
    images: new Set<Media>([
      {
        id: 2,
        url: "https://example.com/another-product-image.jpg",
      },
      {
        id: 3,
        url: "https://example.com/another-product-image2.jpg",
      },
    ]),
  },
];
