import { Toaster } from "@/components/ui/toaster";
import "../../globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "SManager",
  description: "Generated by Next.js",
};

import { Open_Sans } from "next/font/google";
const font = Open_Sans({ subsets: ["latin"] });

export default function SubRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen items-center justify-center">
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
